version: '3.8'

services:
  app:
    image: demo-crud-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 	# port communication
      - "15672:15672" 	# Port admin front RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: admin1234
